services:
  jarvis:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./jarvis/memory:/app/jarvis/memory
      - ./jarvis/debug_logs:/app/jarvis/debug_logs
      - ./.env:/app/.env
    environment:
      - OLLAMA_HOST=ollama:11434
      - LOCAL_MODEL_BASE_URL=http://ollama:11434/api
    depends_on:
      - ollama
    command: python app.py --web --host 0.0.0.0 --port 3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_INTEL_GPU=false
      - OLLAMA_NOHISTORY=true
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:11434/api/version || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  ollama_data:
